import logging

# SQL Schema defined for the application
# Includes PostGIS extension and the main properties table
SCHEMA_SQL = """
-- Habilita a inteligência geográfica (PostGIS)
CREATE EXTENSION IF NOT EXISTS postgis;

-- Cria a tabela unificada de Propriedades
CREATE TABLE IF NOT EXISTS propriedades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    
    -- Quem é o dono?
    user_id UUID NOT NULL, 
    nome_proprietario TEXT NOT NULL,
    email_proprietario TEXT,
    
    -- O que é o imóvel?
    tipo_imovel VARCHAR(10) CHECK (tipo_imovel IN ('RURAL', 'URBANO')),
    nome_imovel TEXT, 
    
    -- Dados Rurais Específicos (JSON para flexibilidade)
    metadados_rurais JSONB, 
    
    -- Dados Urbanos Específicos
    metadados_urbanos JSONB,

    -- O MAPA (A Geometria Mágica)
    geometria GEOMETRY(Polygon, 4326), 
    
    status VARCHAR(20) DEFAULT 'PENDENTE'
);

-- Índices para performance
CREATE INDEX IF NOT EXISTS idx_propriedades_geom ON propriedades USING GIST (geometria);
CREATE INDEX IF NOT EXISTS idx_propriedades_user_id ON propriedades (user_id);
"""

def ensure_schema(conn):
    """
    Ensures that the database schema is initialized.
    Uses CREATE IF NOT EXISTS, so it's safe to run multiple times.
    """
    try:
        cur = conn.cursor()
        # Execute the schema script
        cur.execute(SCHEMA_SQL)
        conn.commit()
        cur.close()
        logging.info("Database schema verified/initialized.")
    except Exception as e:
        logging.error(f"Error initializing database schema: {e}")
        conn.rollback()
        # We don't raise here to allow the connection to be returned, 
        # but subsequent queries might fail if schema is wrong.
