-- Habilita a inteligência geográfica (PostGIS)
-- Certifique-se de que a extensão está disponível no seu Azure Database for PostgreSQL
CREATE EXTENSION
IF NOT EXISTS postgis;

-- Cria a tabela unificada de Propriedades
CREATE TABLE
IF NOT EXISTS propriedades
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP
WITH TIME ZONE DEFAULT timezone
('utc'::text, now
()) NOT NULL,
    
    -- Quem é o dono?
    user_id UUID NOT NULL, -- Vínculo com o sistema de login (pode ser gerado no backend por enquanto)
    nome_proprietario TEXT NOT NULL,
    email_proprietario TEXT,
    
    -- O que é o imóvel?
    tipo_imovel VARCHAR
(10) CHECK
(tipo_imovel IN
('RURAL', 'URBANO')),
    nome_imovel TEXT, -- Ex: "Fazenda Santa Fé" ou "Casa da Rua 10"
    
    -- Dados Rurais Específicos (JSON para flexibilidade)
    metadados_rurais JSONB, 
    -- Ex: {"nirf": "123", "area_ha": 150, "car": "MG-..."}
    
    -- Dados Urbanos Específicos
    metadados_urbanos JSONB,
    -- Ex: {"iptu": "999", "tem_esgoto": true}

    -- O MAPA (A Geometria Mágica)
    geometria GEOMETRY
(Polygon, 4326), -- O desenho do lote/fazenda (SRID 4326 = Lat/Long GPS)
    
    status VARCHAR
(20) DEFAULT 'PENDENTE' -- PENDENTE, ANALISE, REGULARIZADO
);

-- Índices para performance
CREATE INDEX
IF NOT EXISTS idx_propriedades_geom ON propriedades USING GIST
(geometria);
CREATE INDEX
IF NOT EXISTS idx_propriedades_user_id ON propriedades
(user_id);
